# Name of the workflow
name: Unit and Integration tests
# This work flow is triggered when pull requests are opened or updated
on: [pull_request]
# A workflow run is made up of one or more jobs.
# A workflow run is made up of one or more jobs.
jobs:
  # id of job, a string that is unique to the "jobs" node above.
  iPhone:
    # Creates a build matrix for your jobs. You can define different
    # variations of an environment to run each job in.
    strategy:
      # # A set of different configurations of the virtual environment.
      matrix:
        device:
          - "iPhone 11 Pro Max (13.1)"
      # When set to true, GitHub cancels all in-progress jobs if any matrix job
      # fails.
      fail-fast: true
    # The type of machine to run the job on.
    runs-on: macOS-latest
    # Contains a sequence of tasks.
    steps:
      # Clone repo to runner
      - name: Clone repository
        uses: actions/checkout@v4
      # Step for installing Flutter SDK
      - name: Download Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable # or: beta, master (or main)
      # Unit Tests
      - name: Run Unit tests
        run: "flutter test"

      # Startup iOS Sim
      - name: Start Simulator

        #   xcrun simctl boot "${UDID:?No Simulator with this name found}"
        uses: futureware-tech/simulator-action@v3
        with:
          model: "iPhone 14"
      # Driver Tests
      - name: "Run Flutter Driver tests"
        run: "flutter drive --target=test_driver/app.dart"